# Use absolute path!!!
path: /content/Petrol-tags-detection.-3 # dataset root dir
train: ../train/images
val: ../valid/images
test: ../test/images

names:
  [
    "95",
    "circlek",
    "cost",
    "disel",
    "efecta-diesel",
    "lpg",
    "orlen",
    "prices",
    "verva-98",
    "verva-diesel",
    "wild-bean",
  ]
