# Use absolute path!!!
path: C:\Users\janek\notebooks\petrol-prices-object-detection\custom_data\roboflow\dataset-v2 # dataset root dir
train: C:\Users\janek\notebooks\petrol-prices-object-detection\custom_data\roboflow\dataset-v2\train\images
val: C:\Users\janek\notebooks\petrol-prices-object-detection\custom_data\roboflow\dataset-v2\valid\images

# Classes
names:
  0: circlek
  1: orlen
  2: prices
  4: widl-bean
